## Data science Life cycle:

Involves 6-7 steps:
1. Business Understanding.
2. Data Preparation.
3. Data Munging/ Data Wrangling.
    - feature selection.
    - EDA tool.
4. Model trianing.
5. Model evaluation.
6. Model Deployment.
    - aws
    - IBM watson studio.
7. Model tracking.

## Data Analysis Libraries:
- Numpy
- Pandas
- Matplotlib
- Seaborn
- Scipy

## Numpy: 
- Numerical Python.
- Developed in 2005 by Travis oliphant.
    - Zero dimensional array.
    - Single dimensional array.
    - Two dimensional array.
    - Multi dimensional array.
- linear algebra, Fourier transforms, materics.

In [3]:
import numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
np.__version__

'1.20.1'

## Creating Array's:

In [7]:
import numpy as np
x = np.array(23)
print(x)

23


In [9]:
# check dimension.
np.ndim(x)

0

In [10]:
# 1D-array

x1 = np.array([12, 23, 4, 5, 6])
print(x1)
print(np.ndim(x1))

[12 23  4  5  6]
1


In [14]:
# 2D-array

x2 = np.array([[1, 22, 5], [1, 3, 4]])
print(x2)
print("dimension of x2:",np.ndim(x2))

[[ 1 22  5]
 [ 1  3  4]]
dimension of x2: 2


In [15]:
# to get the number of elements in x2 array

np.size(x2)

6

In [17]:
# To get number of rows and columns

print("number of rows and columns in x2:",np.shape(x2))

number of rows and columns in x2: (2, 3)


### 3D-array

- `[ [ [ ] ] ]`

In [18]:
import numpy as np
x3 = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
print(x3)
print("Dimension of x3:",np.ndim(x3))
print("Elements of x3:", np.size(x3))
print("Shape of x3:", np.shape(x3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of x3: 3
Elements of x3: 9
Shape of x3: (1, 3, 3)


## Methods to create arrays
- Zeros
- Ones
- Linspace
- Logspace
- Arange
- randon.rand

In [26]:
a0 = np.zeros(3, dtype = int)
a0

array([0, 0, 0])

In [27]:
a1 = np.ones(5, dtype = int)
a1

array([1, 1, 1, 1, 1])

In [30]:
a1 = np.ones(5, dtype = int)
print(a1)
a2 = a1.reshape(5, 1)
print("reshape of a1 into a2:", a2)
a3 = a1.reshape(1, 5)
print("reshape of a1 into a3:", a3)

[1 1 1 1 1]
reshape of a1 into a2: [[1]
 [1]
 [1]
 [1]
 [1]]
reshape of a1 into a3: [[1 1 1 1 1]]


In [35]:
# 1 is start value, 10 is stop value, 2 is step value.

a = np.arange(1, 12, 2)
print(a)
print("Dimension:", np.ndim(a))
print("Elements:", np.size(a))

[ 1  3  5  7  9 11]
Dimension: 1
Elements: 6


### possibililties to reshape 6 elements
- (1, 6)
- (2, 3)
- (3, 2)
- (6, 1)



In [39]:
a1 = a.reshape(2, 3)
print(a)
print(a1)

[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]


In [40]:
a1 = a.reshape(2, 6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [43]:
l1 = np.logspace(1, 5)
print(l1)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


In [44]:
l1 = np.logspace(1, 5, 3)
print(l1)

[1.e+01 1.e+03 1.e+05]


In [47]:
l1 = np.logspace(1, 5, 1)
print(l1)

[10.]


In [50]:
l2 = np.linspace(1, 5, 6)
l2

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [56]:
r = np.random.rand(1, 2)
print(r)

[[0.50392341 0.51529964]]


In [57]:
r1 = np.random.randint(1, 10)
print(r1)

8


In [58]:
r2 = np.random.randn(1, 10)
r2

array([[-1.17151248,  2.01121977,  0.39785513, -0.0493953 , -0.73483266,
         1.03487683,  0.08119897,  0.46941515, -0.26064149,  0.27198548]])

In [59]:
np.ndim(r2)

2

In [62]:
r3 = r2.flatten()
r3

array([-1.17151248,  2.01121977,  0.39785513, -0.0493953 , -0.73483266,
        1.03487683,  0.08119897,  0.46941515, -0.26064149,  0.27198548])

In [63]:
np.ndim(r3)

1

## Accessing elements in arrays:
1. indexing
    - +ve
    - -ve
2. slicing -[start:stop:step]
3. loop
    - for
    - while